name: Push Container to Heroku

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku container:login
          git remote add heroku https://git.heroku.com/${{ secrets.HEROKU_APP_STAGING }}.git
      - name: Build and push
        run: git push -f heroku origin/master:master
