name: Push Container to Heroku

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku container:login
          heroku git:remote --ssh-git -a ${{ secrets.HEROKU_APP_STAGING }}
      - name: Build and push
        run: git push -f heroku origin/master
